### PR TITLE
Additions to Longleaf chapter

### PR DESCRIPTION
**Pull request by dpritchLibre**
Opening up a PR for continued additions to the Longleaf chapter.  These additions are a work in progress.

### CODE REVIEW

**Comment by BarkleyBG** [comment]
This doc seems to have some good infromation. Could you just drop it in as a reference in the bibliography? 
http://statistics.berkeley.edu/computing/servers/cluster

**Comment by dpritchLibre** [comment]
Yes, this looks good!  I have a collection of bookmarks for pages about Slurm, and I'll add them all in in batch

**Comment by BarkleyBG** [comment]
Let's merge this in. By March 1? Instead of letting it get stale.

**Comment by BarkleyBG** [comment]
Maybe we should try this?
https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

I think I could then push edits to this branch on your fork. Like, merging in the conflicts.

**Comment by dpritchLibre** [comment]
This PR is ready to be merged.  Rather than having completed what I set out to do, I'm abandoning the work on the Longleaf section for the time-begin, with the intention of picking it up later.

Thanks!

**Pull request merged**
