### PR TITLE
Windows CLI content

### PR DESCRIPTION
**Pull request by dpritchLibre**
Began filling in the section about accessing a Unix CLI from Windows.

This PR is _not_ ready to be merged yet.

### CODE REVIEW

**Comment by dpritchLibre** [comment]
This PR is in response to issue #3

**Comment by dpritchLibre** [comment]
This branch ready to be considered for merging.

**Comment by BarkleyBG** [comment]
The content looks very good. I haven't read through every line of edits, but I did look at the two big additions regarding CLI on Windows and copy/paste. They're great.

My develop branch has moved forward since you last fetched. Would you mind updating your branch with the new sectioning, and managing the conflicts in Chapters 1 (*nix intro) and 2 (shell intro)? I may have to manage the conflicts in preamble_settings, which is fine.

**Comment by dpritchLibre** [comment]
Okay, updated

**Pull request merged**
