### PR TITLE
Inline code highlighting

### PR DESCRIPTION
**Pull request by dpritchLibre**
This PR modifies `listings` `lstinline` command to highlight said the command.  `lstinline` works just like `\verb` except that it is more customizeable, at least as far as I can tell.  So for example you can use

    here is an example command \lstinline{some special characters &$'} and more stuff

or you equivalently any other delimiter instead of  `{ }` such as

    now I have \lstinline!brackets { ... }! in the verbatim code.

Getting the highlighting right may take two compilations.  I have left the `\code` command for filenames and paths and other code.  

--------------------

This solution has one major drawback: it will not break over lines properly on its own, so you have to manually add breaks as in `\lstinline!as.numeric(!\lstinline!my_variable))!` when you have long expressions.    Trying to find a good solution for this has demonstrated one of LaTeX's characteristics: anything is possible, but some things that seemingly should be easy can actually be extremely difficult.  Any of the various solutions that I considered had advantages and drawbacks.  Another reasonable choice would automatically break over lines, but any special characters had to be escaped and wouldn't always print correctly (like the carot ^, for example).  I think that this solution is better.

### CODE REVIEW

**Comment by BarkleyBG** [comment]
Not sure I totally understand the issue. Is this to replace `\code{}`?

**Comment by dpritchLibre** [comment]
As a supplement to `\code`.  You had mentioned the other day that it would be nice to have a highlighted code option in a style similar to e.g. GitHub Markdown, so this was my attempt to implement that.

**Comment by BarkleyBG** [comment]
ok, cool thanks. I'll take a look later in the week.

**Comment by BarkleyBG** [comment]
I was working with a MWE of this branch locally today, and I was having trouble with it. In particular, if I added

```
\lstinline{foo}
```
then it would show up in typewriter font, but if I compiled

```
\lstinline{foo}
\hlcode{bar}
```
then `foo` would have grey highlighter background, and `bar` would be typewriter.

Anyways, let's work this out next week? After the other things; it's not urgent.

**Comment by dpritchLibre** [comment]
Yes, that's right. lstinline should have the highlighter and it may take two compiles to show up.  But I'm confused - I didn't think that I left an hlcode command?

**Comment by BarkleyBG** [comment]
Hm, I'll have to check - I had seen that one of the commits added a `hlcode` command, but maybe it was removed in a later commit. Maybe that's my mistake.

**Comment by dpritchLibre** [comment]
Yes, you're correct, one of the commits did define an `hlcode` command that was later removed.  I left it in the history in case we did decide we preferred that option to the current offering, so that we could just roll back the branch.  The `hlcode` was the solution that "would automatically break over lines, but any special characters had to be escaped and didn't always print correctly" that I mentioned in the top of this thread.  We can discuss the various merits of the two options.

**Comment by dpritchLibre** [comment]
@BarkleyBG This is a friendly reminder to please give this branch another try and merge it in if you are satisfied with the results.

**Pull request merged**
