### PR TITLE
Alert reader to challenging material

### PR DESCRIPTION
**Pull request by dpritchLibre**
Adds a command `\danger` that places the `\bcattention` symbol from the `bclogo` package in the right margin.  The symbol can be seen on page 11 of http://ctan.math.utah.edu/ctan/tex-archive/graphics/bclogo/doc/bclogo-doc.pdf.

The use case that I have in mind is to place it at the beginning of a paragraph.  So e.g.

    \danger This paragraph is really hard.  And so on and so forth..

Addresses issue #8 (single digits!!)

### CODE REVIEW

**Comment by BarkleyBG** [comment]
Single digits??! The dark ages!

This does beg the question... why were you looking into a french TeX symbols doc??!

I'm all for this. Good to merge?

**Comment by dpritchLibre** [comment]
Haha.  Yes, that did make it a little challenging!  Luckily I was able to look at just the code and output, and in the end all I used was the symbol.

Yeah I think it's safe to merge.

**Comment by BarkleyBG** [comment]
addresses #8

**Comment by BarkleyBG** [comment]
closes #8

**Pull request merged**
