### PR TITLE
Iss27 standardize names

### LINKED ISSUE #27: Examples should be standardized (same username)
We should define some standardized definitions to use throughout the document.

For example, there's already `\def\r/{\textsf{R}}`. Perhaps we should define `\def\userid/{userid}` to be used throughout? There are other examples, like `\hostname/`

I think you could get it to pass to the listings envornments, too. Something like the following:

```
\newcommand\terminal[1] {
    \begin{lstlisting}[style=terminal]
        \userid/@\hostname/:~$ #1
    \end{lstlisting}
}
```

I can begin a branch on this from Develop, but may need your help @dpritchLibre

### PR DESCRIPTION
**Pull request by BarkleyBG**
- bumps version
- fixes a couple references
- finds and fixes a few dangling un-standardized userid names

I think there's enough here to close #27 finally. OK to merge @dpritchLibre ?

### CODE REVIEW

**Comment by dpritchLibre** [comment]
I'm all for closing stale issues!

**Comment by dpritchLibre** [comment]
BTW, I'm not really sure where to write this, but I would prefer not to put things like StackOverflow pages and other single-issues web pages in the bibliographies.  I think the bibliographies should be reserved for bigger-picture things like books, papers, manuals, stuff like that.  The little stuff I think we can just link to inline.  Just something to think about moving forward.

**Comment by BarkleyBG** [comment]
Yes, that's a good point on the bibliographies vs. SO posts. So you suggest we omit SO posts from the bibliography (unless it's a really good/extensive answer, perhaps), and just `\href` to them instead?

**Comment by BarkleyBG** [comment]
I'm closing the PR and merging so you can pull it into your topic branch. Feel free to continue the bibliography conversation though

**Comment by dpritchLibre** [comment]
> Yes, that's a good point on the bibliographies vs. SO posts. So you suggest we omit SO posts from the bibliography (unless it's a really good/extensive answer, perhaps), and just \href to them instead?

Yes, exactly, unless as you say it was more substantial than the usual (for example, [this SO post](https://stackoverflow.com/q/388242) would certainly qualify!)

**Pull request merged**
