### PR TITLE
References framework

### PR DESCRIPTION
**Pull request by dpritchLibre**
This PR addresses issue #25 by trying to create a new framework for references.  The key objectives are (i) providing chapter-by-chapter references as well as (ii) a mechanism to write a description about each reference, when desired.

This framework does make a major change in that it switches to the BibLaTeX references framework.  As far as I can tell, this will not require any changes from authors or contributers with the exception of the commands that are used to invoke citations.  The list and descriptions of the citation commands are found in sections 3.8.1-3.8.2 (page 95) of the BibLaTeX user's guide available at http://ctan.math.washington.edu/tex-archive/macros/latex/contrib/biblatex/doc/biblatex.pdf.  So far I've used the `\textcite` command for inline citations, and the `\nocite` command for citations that I want to show up in the bibliography but not inline.

This is still a work in progress, so you don't have to merge it right away.  On the other hand, if you plan to add some citations to whatever you are currently working on, then you may want to consider merging it first.

### CODE REVIEW

**Comment by dpritchLibre** [comment]
I'm making what I'd consider to be some good progress on this task.  However, I've asked the `tex.stackexchange` community for some help on a few typesetting details.  The link is https://tex.stackexchange.com/questions/401879 if you want to check out the responses, if any.

**Comment by BarkleyBG** [comment]
Looks like you've already got a great response!




On Nov 17, 2017, at 8:16 PM, dpritchLibre <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm making what I'd consider to be some good progress on this task. However, I've asked the tex.stackexchange community for some help on a few typesetting details. The link is https://tex.stackexchange.com/questions/401879 if you want to check out the responses, if any.

**Comment by dpritchLibre** [comment]
I'm happy to report that I think that the references framework is of sufficient maturity to be merged into the `develop` branch, pending your approval.  Rather than try to explain to you exactly how things work here, what I've done instead is to try to provide a thorough description in `CONTRIBUTING.md`.  Since we want this document to live on after we leave here and this process is one of the more complicated ones, it is important that things are clearly laid out there.  So what I would ask you to do, when time permits, is to read through the references section description there, and see if everything is clear or what else I could add to clarify things.

The `CONTRIBUTING.md` file can be read [here](https://github.com/dpritchLibre/LCC/blob/issue25_references/CONTRIBUTING.md).  On the other hand, you are welcome to merge the PR without having yet read the documentation in detail. :smiley: 

Addresses issue #25

**Comment by dpritchLibre** [comment]
P.s. at some point I would like to sit down with you and ensure that everything works on Windows machines.  Also, I believe that one of the files, `latex/references/create_global_refs.sh`, will need to live on your computer with Unix-style line endings.  So I think we will need to introduce a project `.gitattributes` file to handle this complication.  Just mentioning so as to plant a seed in your mind for future.

**Comment by BarkleyBG** [comment]
This is great!

It seems like we may need to iterate on this for a bit (because of the OS's). I created a new branch, `iss25_refs`, and pushed it to the repo. Could you change your PR to this new topic branch? Then I'll merge it in to the topic branch so we can fight any fires outside of `develop`.

Sound good?

**Comment by dpritchLibre** [comment]
Would I be able to start my branches from `iss25_refs` then?  I'd like to do all of my work downstream from this branch moving forward.

**Comment by BarkleyBG** [comment]
Perhaps. I worry that there may be issues between the OS's, and so we would need to change a few things. I understand though, so I'll try to hurry the merge along

**Pull request merged**
