### PR TITLE
Foundational BIOS cluster topics - not ready to merge

### PR DESCRIPTION
**Pull request by dpritchLibre**
I've created this PR just to make available a few sections that I had been working on.  I've had to set this project aside lately though, and I don't expect to make much progress in the next few weeks.

The topics skeleton that I've added to chapter 5 in the PR are the following:
1.  Logging in to the Diamond and Sapphire login nodes (basically just refer to + link to chapter 0 and chapter 2)
2.  The shell environment on the cluster
3.  Locating available software on the cluster
4.  Installing software on the cluster
5.  Transferring files to and from the BIOS filesystem
    * text-based UI section just refers back to chapter 2
    * GUI section introduces SSH Communications Security SFTP client and FileZilla
6.  Editing files on the cluster

There is some partial work done so far for sections 1, 3, 4, and 5.  Sections 2 and 6 are completely blank.

------------------------------------------------------------------

I'm thinking that it might be a good fit to place these foundational topics in chapter 5, along with the existing "four quadrants of R" and interactive and batch Slurm jobs existing material.  I think you could also make a case for putting this new material in its own chapter.  I'll be interested to hear your thoughts on the topics and placement.

### CODE REVIEW

**Comment by BarkleyBG** [comment]
I'd like to merge this in sooner rather than later. I have a topic branch, we have a develop branch, and this is a lot of important information in this branch. 

Is there anything you want to take care of before this gets merged in?

One reason why I want to merge this in is because I actually might have time to start proofreading, and it's easier to start catching inconsistencies when we have all the work in the same place.

**Comment by dpritchLibre** [comment]
Sure, I think merging would only be a good thing if it allows more eyeballs to catch mistakes and make improvements.

This is maybe a dumb question, but would it be sensible workflow to merge in the branch but to leave the PR open?  The idea being that I'm continuing to work on the branch anyway.  The alternative I guess would be to close the PR and open a new PR with title of "continued edits on chap5" or something.

**Comment by BarkleyBG** [comment]
I'm thinking to merge the branch into develop by closing this PR. You can of course continue work on this branch (and open a new PR). 

sound ok?

**Comment by dpritchLibre** [comment]
Sounds good

**Pull request merged**
