### PR TITLE
Reorder chapters and change filenames

### LINKED ISSUE #109: Restructure chapters again
Restructure to chapters 0 through 10

### PR DESCRIPTION
**Pull request by dpritchLibre**
This PR fixes #109.

Please take a close look at this PR and make sure that I did it correctly.  It was a little tricky getting everything to compile again once I moved things around.

The main things that are done in this PR are the following:
1.  Change the ordering of the chapters as described in #109.  This consisted of the following things:
    * switch the order of the Slurm arrays chapter and the R tips and tricks chapter (chapters 8 and 9)
    * merge the clusters courtesies chapter into the Slurm arrays chapter
    * insert a yet unwritten chapter for taking a detailed look at Slurm commands
2.  Changing the chapter and reference filenames to reflect the new organization
3.  Changed the chapter name for chapter 6 to "Statistical Software on the BIOS cluster" to be more general since we describe running MATLAB and SAS etc.  Am open to suggestions on this - it is included in the PR b/c I wanted the filename to reflect the title if we do decide to change it to something

### CODE REVIEW

**Comment by BarkleyBG** [comment]
Seems like we've got some merge conflicts. Would you prefer to take care of these before or after I merge in my edits today (mostly chapter 0 stuff; ill throw up the PR but I want to commit 1-2 things today)

**Comment by BarkleyBG** [comment]
1. can you remove `cluster_guide_develop.pdf`?
1. #119 is ready to merge in. It's not perfect but definitely a big improvement to chapter 0.  Should I merge that in before this one here?
1. I notice that you labeled the Slurm section with `\label{chp:*}` instead of `\label{sec:*}`. Would you mind if I changed all chapter labels to `chp:*` instead of `sec:*`? I think I could do with some `grep/sed/awk` command.

**Comment by dpritchLibre** [comment]
Great, yeah go ahead and merge in #119 if you like.  Yeah if you want to change the labels to chap then I think that would be helpful.

**Comment by BarkleyBG** [comment]
2. I merged #119. 
3. I'll file an issue and personally take care of the sec/chp labels after this gets merged in. I'll start a new PR - i don't want to muck with your topic branch

**Comment by dpritchLibre** [comment]
I just filed the issue

**Comment by dpritchLibre** [comment]
I think this branch is ready to be merged in now

**Pull request merged**
