### PR TITLE
Chapter 2 revisions

### PR DESCRIPTION
**Pull request by dpritchLibre**
Beginning chapter 2 revisions.  This branch is _not_ ready to be merged yet.

### CODE REVIEW

**Comment by BarkleyBG** [comment]
I'm changing the name as a reminder to me not to merge it. 

When you're ready, just leave a comment (that's been really helpful; thanks) and change the title.

**Comment by BarkleyBG** [comment]
Regarding the nice use of `grep` in #79  - 

I know you've got a `grep -rn` example in the text. Does it make sense to add another example within the context of stats/R programming? 
- It could be brief (e.g., no need to actually "run" it and show output)
- possible example: "Let's say you're looking for the script where you created `my_important_scatterplot.pdf`, but you can't remember the file in which it lives. So, use `grep -rn my_important_scatterplot.pdf` and it should show up"

**Comment by BarkleyBG** [comment]
Should I merge chapter 1 into develop so you can have the appendices?

**Comment by dpritchLibre** [comment]
I thought that the appendices were in chapter 0, no?  And didn't you already do that?  Maybe not, I'm getting lost with all of these branches now.

I'm in the middle of a pretty intense merge right now.

**Comment by dpritchLibre** [comment]
Yes, I see now that chapter 0 isn't in `develop` yet.  Yeah I guess it would be helpful to have it in at some point, thanks for asking.

**Comment by BarkleyBG** [comment]
Sorry, my mistake. I think they're in Chapter 0. Should I merge that into develop? Lemme know when you're done with your octo-merge! Lol

**Comment by dpritchLibre** [comment]
Haha, yeah man go for it!!  I just got the doc to compile, we're at 134 pages and that's before your work in chapter 0.

**Comment by dpritchLibre** [comment]
I'm proud to say that this branch is finally **ready to be merged**.  Check it out once you merge it in, I think you'll like what you see!

I found that writing this chapter, while being important foundationally for the rest of the document, to be somewhat boring at times.  I'm excited to get to start thinking and writing about the actual cluster computing side of things.

**Pull request merged**
