### PR TITLE
A branch with an overview of *nix and basic shell operations

### PR DESCRIPTION
**Pull request by dpritchLibre**
This is some text for two possible sections to add to the LCC guide.  One section is an overview of Unix / Linux, and the second is an overview of command-line interface and an introduction to some of the fundamental Unix programs / commands.

This is an early pull request as the sections are by no means complete, but merely an opening of a GitHub dialogue.

### CODE REVIEW

**Comment by BarkleyBG** [comment]
Spell my name correctly and I *MIGHT* merge this :stuck_out_tongue_winking_eye:

**Comment by dpritchLibre** [comment]
I fixed the misspelling (sorry!) using git rebase and then git push --force.  I just wonder now if that's messed up the pull request or if it's okay since nothing has yet been merged.

**Comment by dpritchLibre** [comment]
I think that all of the content that I had in mind for these sections is there now, but I think everything needs a second pass to clean things up and reorganize some of the sections.  Also I'm debating changing the appearance of the terminal code environments.  Right now it is white on black, which I think looks nice by itself, but dropped in between lines of text it is somewhat visually distracting.

**Comment by BarkleyBG** [comment]
Let's avoid force pushing in future pull requests for now. It seems like we could follow the [examples in the bible on iterating on a PR ](https://git-scm.com/book/en/v2/GitHub-Contributing-to-a-Project).

I'll think on the b&w coloring issue. Seems reasonable to have b&w, but it may be too distracting inline.

**Comment by BarkleyBG** [comment]
This (excellent) work by @dpritchLibre has been integrated into the develop branch. 

I'm considering this PR closed even though the document is not fully written (see #3 )

**Pull request closed without merging**
