### PR TITLE
Fix page numbering

### PR DESCRIPTION
**Pull request by dpritchLibre**
Addresses #38.  Also rolled in is an added section in chapter 8 about the shell environment on Longleaf.  I had to fix the page numbering so that I could see how big I could make one of the images.

### CODE REVIEW

**Comment by dpritchLibre** [comment]
Also, I deleted one word in chapter 6 ("annoyingly"), but it looks like my editor deleted a bunch of trailing whitespace in the file if you are wondering what is going on there.

**Comment by BarkleyBG** [comment]
ugh, whitespace and line endings. This is hard to review. I can merge it if you think it's good.

I think we should discuss whether I should change my global options to "commit with LF" 
seems relevant > https://help.github.com/articles/dealing-with-line-endings/

**Comment by dpritchLibre** [comment]
Just ignore the diff for chapter 6 and maybe it's not so bad?  I think it's safe to merge.. maybe just merge it locally and make sure that everything still compiles and looks okay, and then if so you can push the merge back to the remote?  If not then you can roll it back with `git reset`.

I kind of screwed the pooch by doing the line numbering in with the addition to chapter 8.  The problem was that I needed to see the line numbers in order to fit one of the figures properly.

**Comment by BarkleyBG** [comment]
nice work with the page numbering!! 👍

**Pull request merged**
